### ISSUE TITLE
interface not working on raspbian, kernel 5.15.84-v7+

### ISSUE THREAD

**Issue by mdmvgithub** [lwfinger/rtl8192du#100]
Hi,
I have compiled the driver on raspbian, kernel 5.15.84-v7+
modprobe works fine, but when I perform 'ifconfig wlan1' or 'ip address' , process gets locked doing:

ioctl(4, SIOCGIFADDR, {ifr_name="wlan1

Initialization seems ok:

[ 2128.725753] 8192du: loading out-of-tree module taints kernel.
[ 2128.774838] RTL8192DU: module init start
[ 2128.774856] RTL8192DU: rtl8192du v4.0.10_25039.20171107
[ 2128.916588] RTL8192DU: rtw_ndev_init(wlan1)
[ 2128.918601] usbcore: registered new interface driver rtl8192du
[ 2128.918621] RTL8192DU: module init ret=0

To compile, it has been necessary to do (in the arch directory of linux headers)
ln -s arm  armv7l
The only compilation problem is a warning:

rtl8192du/os_dep/ioctl_cfg80211.c: In function ‘rtw_get_systime_us’:
./include/asm-generic/div64.h:222:28: warning: comparison of distinct pointer types lacks a cast
  222 |  (void)(((typeof((n)) *)0) == ((uint64_t *)0)); \
      |                            ^~
/root/sources/rtl8192du/os_dep/ioctl_cfg80211.c:348:9: note: in expansion of macro ‘do_div’
  348 |  return do_div(ts, 1000);
      |         ^~~~~~

**Comment by mdmvgithub** [comment]
Having not heard from the subject, and wanting to make my cheap 8192du usb work in raspberry pi 3, I have resumed this matter. I have verified, looking at the releases of libreelec, that this module does not work in the 6.1 and 5.15 kernels, but it does in 5.10.

I have downgraded from raspbian and it works correctly.
In case someone has the same need, waiting for a better solution, these are the steps:

```
wget https://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/raspberrypi-kernel-headers_1.20220118-1_arm64.deb
dpkg -i raspberrypi-kernel-headers_1.20220118-1_arm64.deb
rpi-update b4145cfaa838049fcc1174d1311a98a854703c29
echo raspberrypi-bootloader hold | dpkg --set-selections
echo raspberrypi-kernel hold | dpkg --set-selections
echo raspberrypi-kernel-headers hold | dpkg --set-selections
reboot
```
And now compile and install the rtl8192du module

Use
```
echo dtoverlay=disable-wifi >>/boot/config.txt
```
To disable onboard wifi

**Comment by lwfinger** [comment]
I do not drop everything to "fix" a warning. It still compiles correctly.
