### ISSUE TITLE
DESTDIR symbol is required for non-root installs/commit 242ffe198e is broken

### ISSUE THREAD

**Issue by graysky2** [lwfinger/rtl8192du#29]
This commit (https://github.com/lwfinger/rtl8192du/commit/242ffe198e36be71c256f3a3ad63a3e0eafe260e) breaks the install process since DESTDIR is required for non-root installs like those a for distro packages.  For example, try this:
```
% make DESTDIR=foo install              
install -d /usr/lib/modules/3.18.2-1-custom/kernel/drivers/net/wireless/
install -m644 8192du.ko  /usr/lib/modules/3.18.2-1-custom/kernel/drivers/net/wireless/
install: cannot create regular file ‘/usr/lib/modules/3.18.2-1-custom/kernel/drivers/net/wireless/8192du.ko’: Permission denied
Makefile:155: recipe for target 'install' failed
make: *** [install] Error 1
```

Rather than directing the files to ./foo/... it tries to do it to the live filesystem.

**Comment by lwfinger** [comment]
Commit reverted.
