### ISSUE TITLE
Question: no-cfg80211 / no_cfg80211

### ISSUE THREAD

**Issue by wmbr** [lwfinger/rtl8192du#56]
Sorry to bother you, but I couldn't help noticing that you recently abandoned a lot of commits on no_cfg80211 in favor of a new branch no-cfg80211 and reset master accordingly.
Is it possible to briefly explain the difference between these two?

**Comment by lwfinger** [comment]
That was a typo. There has been a lot of work lately at fixing the problems with a cfg80211 build. It has been working very well, and I suggest that none of the non-cfg80211 branches be used.
