### ISSUE TITLE
Two interfaces but one USB device

### ISSUE THREAD

**Issue by mrkskwsnck** [lwfinger/rtl8192du#65]
Hello to all,

I am happy to successfully compiling and running this kernel driver for my **RTL8192DU** device, which is an _no name_ USB device, on my Manjaro Linux system.

The only thing that bothers me is that I have two wireless interfaces in my network manager, which is somewhat annoying -_-

![grafik](https://user-images.githubusercontent.com/486983/43995520-0bd42456-9daf-11e8-83ff-518ef504c19d.png)

Also `$(iwconfig)` provides the following output with two wireless interfaces.

```
lo        no wireless extensions.

eno1      no wireless extensions.

wlp0s20u4  IEEE 802.11gn  ESSID:"wiesbaden.freifunk.net"  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency:2.437 GHz  Access Point: 7A:12:B6:76:4A:68   
          Bit Rate:144.4 Mb/s   Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality=100/100  Signal level=98/100  Noise level=0/100
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

wlan0     IEEE 802.11gn  ESSID:"wiesbaden.freifunk.net"  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency:2.437 GHz  Access Point: 7A:12:B6:76:4A:68   
          Bit Rate:144.4 Mb/s   Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality=100/100  Signal level=98/100  Noise level=0/100
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
```

Why is that? Hopefully someone can provide the answer and also a fix.

Thanks in advance and best regards!

**Comment by lwfinger** [comment]
This is a feature, not a bug. The default configuration is set to provide dual interfaces so that one can be used as an AP, and the other as a STA. To remove the extra one, go to file include/autoconf.h and change the statement defining CONFIG_CONCURRENT_MODE Setting that macro to 0 will eliminate the extra interface.

**Comment by mrkskwsnck** [comment]
Indeed, I did not know that. How do I know which one is A(ccess)P(oint) and/or STA(tion)/Client? And which should I use?

**Comment by lwfinger** [comment]
They are identical. You choose.

**Comment by mrkskwsnck** [comment]
Thank you for the clarification.
