### ISSUE TITLE
Thank you for this driver, please update this for Linux Kernel 5.2 series.

### ISSUE THREAD

**Issue by phd21** [lwfinger/rtl8192du#77]
Dear  lwfinger, or whoever maintains this, 

Thank you for this driver, please update this for Linux Kernel 5.2 series. FYI: This driver worked well for me and the Linux Kernel 5.1 series.

This is the only driver I could install that would allow my one dual-band USB WiFi adapter to work in Linux Mint 19.x or KDE Neon both based on Ubuntu 18.04 Bionic.

Amazon.com: Bolse USB Network Adapters, Laptop Computer Network Card Adapters, Dual-Band N600 USB Wireless WiFi Adapter Optimized for HD Video & Gaming, 2.4GHz 300Mbps/5Ghz 300Mbps: Computers & Accessories
https://www.amazon.com/gp/product/B00JZAB8OI/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1

lsusb shows this as the adapter
Bus 002 Device 002: ID 0bda:8194 Realtek Semiconductor Corp.

sudo modprobe rtl8192du
modprobe: FATAL: Module rtl8192du not found in directory /lib/modules/5.2.4-050204-lowlatency

Best regards,
Phil (phd21)

**Comment by MilhouseVH** [comment]
Both the master and v4.0.10 branches are already compatible with kernel 5.2.y (since 23 May). Perhaps if you explain more about what your actual problem is, maybe an error log showing the actual error(s)?

**Comment by phd21** [comment]
Hi MilhouseVH,

Thank you for the quick response. Perhaps I am using a slightly older version, mine shows May 8 2019. Or perhaps I installed this incorrectly.

Can you please provide a quick paraphrasing of the correct installation instructions for Ubuntu? Do I have to somehow remove the source code from dkms for the older version before using the newer version? I used "git clone" to get the source from here.

dkms status shows below, but not for kernel 5.2.4 I just installed.
8192du, 1.0, 5.1.6-050106-lowlatency, x86_64: installed

lsusb shows this as the adapter
Bus 002 Device 002: ID 0bda:8194 Realtek Semiconductor Corp.

sudo modprobe rtl8192du
modprobe: FATAL: Module rtl8192du not found in directory /lib/modules/5.2.4-050204-lowlatency


Best regards,
Phil (phd21)

**Comment by phd21** [comment]
Hi MilhouseVH, and Anyone else following this post,

Okay, I think it worked with the current version of this driver and Kernel 5.2.4.
This is what I did. Please let me know if this is correct or if it is not correct and if I missed something.

Remove the older driver software from the dkms
sudo dkms remove 8192du/1.0 --all

Then removed any existing source code folder for this driver from my home folder where I download and install this from
rm -r  ~/rtl8192du

Get the newest source code from here.
git clone https://github.com/lwfinger/rtl8192du.git

Added the current source code folder to DKMS
sudo dkms add ~/rtl8192du

Installed the current version into DKMS
sudo dkms install 8192du/1.0

> Kernel preparation unnecessary for this kernel.  Skipping...
> 
> Building module:
> cleaning build area...
> 'make'.................
> cleaning build area...
> 
> DKMS: build completed.
> 
> 8192du.ko:
> Running module version sanity check.
> /usr/sbin/dkms: line 784: find_module: command not found
> modinfo: ERROR: missing module or filename.
>  - Original module
>    - No original module exists within this kernel
>  - Installation
>    - Installing to /lib/modules/5.2.4-050204-lowlatency/kernel/drivers/net/wireless//
> 
> depmod...
> 
> Backing up initrd.img-5.2.4-050204-lowlatency to /boot/initrd.img-5.2.4-050204-lowlatency.old-dkms
> Making new initrd.img-5.2.4-050204-lowlatency
> (If next boot fails, revert to initrd.img-5.2.4-050204-lowlatency.old-dkms image)
> update-initramfs...............
> 
> DKMS: install completed.
> 

Now, I have to reboot and see if it works.

**Comment by phd21** [comment]
Hi MilhouseVH, and Anyone else following this post,

Yeah, it seems to work with the current version of this driver and Linux Kernel 5.2 series because the WiFi adapter is working now. Thank you.

The commands processed this updated driver for the new kernel but did not update the other installed Kernels? Is there a command to have DKMS update the other Kernels and if yes, what is that command?

I have not had much experience with the dual-band WiFI adapters and I do not have a dual-band AC WiFi router. Whenever I use this particular USB WiFi adapter in my KDE systems, the system thinks when running "iwconfig" that I have 2 adapters installed, is this normal with dual-band WiFi adapters or is this something peculiar to this particular WiFi adapter. Does that have something to do with 2.4Ghz and 5Ghz dual-bands? And I can connect using either one?

> wlp#x##y#z#  IEEE 802.11  ESSID:off/any  
>           Mode:Managed  Access Point: Not-Associated   Tx-Power=12 dBm   
>           Retry short limit:7   RTS thr:off   Fragment thr:off
>           Encryption key:off
>           Power Management:off
>           
> 
> wlxe0123456789  IEEE 802.11  ESSID:"XYZ"  
>           Mode:Managed  Frequency:2.462 GHz  Access Point: 
>           Bit Rate=300 Mb/s   Tx-Power=12 dBm   
>           Retry short limit:7   RTS thr:off   Fragment thr:off
>           Encryption key:off
>           Power Management:off
>           Link Quality=65/70  Signal level=-45 dBm  
>           Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
>           Tx excessive retries:0  Invalid misc:0   Missed beacon:0
>

**Comment by lwfinger** [comment]
One thing you need to do is to read the manual on git. Deleting all the files, and doing a git clone is the same as git pull. A lot easier and uses a lot less bandwidth!!
