### ISSUE TITLE
Compile failure against kernel 5.2.5

### ISSUE THREAD

**Issue by dbrazziel** [lwfinger/rtl8192du#78]
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.2.5-200.fc30.x86_64/build M=/usr/src/rtl8192du  modules
make[1]: Entering directory '/usr/src/kernels/5.2.5-200.fc30.x86_64'
  CC [M]  /usr/src/rtl8192du/core/rtw_cmd.o
  CC [M]  /usr/src/rtl8192du/core/rtw_security.o
  CC [M]  /usr/src/rtl8192du/core/rtw_debug.o
  CC [M]  /usr/src/rtl8192du/core/rtw_io.o
  CC [M]  /usr/src/rtl8192du/core/rtw_ioctl_query.o
  CC [M]  /usr/src/rtl8192du/core/rtw_ioctl_set.o
  CC [M]  /usr/src/rtl8192du/core/rtw_ieee80211.o
  CC [M]  /usr/src/rtl8192du/core/rtw_mlme.o
  CC [M]  /usr/src/rtl8192du/core/rtw_mlme_ext.o
  CC [M]  /usr/src/rtl8192du/core/rtw_wlan_util.o
  CC [M]  /usr/src/rtl8192du/core/rtw_pwrctrl.o
  CC [M]  /usr/src/rtl8192du/core/rtw_rf.o
  CC [M]  /usr/src/rtl8192du/core/rtw_recv.o
  CC [M]  /usr/src/rtl8192du/core/rtw_sta_mgt.o
  CC [M]  /usr/src/rtl8192du/core/rtw_ap.o
  CC [M]  /usr/src/rtl8192du/core/rtw_xmit.o
  CC [M]  /usr/src/rtl8192du/core/rtw_p2p.o
  CC [M]  /usr/src/rtl8192du/core/rtw_tdls.o
  CC [M]  /usr/src/rtl8192du/core/rtw_br_ext.o
  CC [M]  /usr/src/rtl8192du/core/rtw_iol.o
  CC [M]  /usr/src/rtl8192du/core/rtw_sreset.o
  CC [M]  /usr/src/rtl8192du/core/rtw_efuse.o
  CC [M]  /usr/src/rtl8192du/hal/hal_intf.o
  CC [M]  /usr/src/rtl8192du/hal/hal_com.o
  CC [M]  /usr/src/rtl8192du/hal/dm.o
  CC [M]  /usr/src/rtl8192du/hal/usb_ops_linux.o
  CC [M]  /usr/src/rtl8192du/hal/rtl8192d_hal_init.o
  CC [M]  /usr/src/rtl8192du/hal/rtl8192d_phycfg.o
  CC [M]  /usr/src/rtl8192du/hal/rtl8192d_rf6052.o
  CC [M]  /usr/src/rtl8192du/hal/rtl8192d_dm.o
  CC [M]  /usr/src/rtl8192du/hal/rtl8192d_rxdesc.o
  CC [M]  /usr/src/rtl8192du/hal/rtl8192d_cmd.o
  CC [M]  /usr/src/rtl8192du/hal/usb_halinit.o
  CC [M]  /usr/src/rtl8192du/hal/rtl8192du_led.o
  CC [M]  /usr/src/rtl8192du/hal/rtl8192du_xmit.o
  CC [M]  /usr/src/rtl8192du/hal/rtl8192du_recv.o
  CC [M]  /usr/src/rtl8192du/hal/rtl8192d_xmit.o
  CC [M]  /usr/src/rtl8192du/hal/Hal8192DUHWImg.o
  CC [M]  /usr/src/rtl8192du/os_dep/osdep_service.o
  CC [M]  /usr/src/rtl8192du/os_dep/os_intfs.o
/usr/src/rtl8192du/os_dep/os_intfs.c:574:22: error: initialization of ‘u16 (*)(struct net_device *, struct sk_buff *, struct net_device *)’ {aka ‘short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *)’} from incompatible pointer type ‘u16 (*)(struct net_device *, struct sk_buff *, struct net_device *, u16 (*)(struct net_device *, struct sk_buff *, struct net_device *))’ {aka ‘short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *, short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *))’} [-Werror=incompatible-pointer-types]
  574 |  .ndo_select_queue = rtw_select_queue,
      |                      ^~~~~~~~~~~~~~~~
/usr/src/rtl8192du/os_dep/os_intfs.c:574:22: note: (near initialization for ‘rtw_netdev_ops.ndo_select_queue’)
/usr/src/rtl8192du/os_dep/os_intfs.c:1710:22: error: initialization of ‘u16 (*)(struct net_device *, struct sk_buff *, struct net_device *)’ {aka ‘short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *)’} from incompatible pointer type ‘u16 (*)(struct net_device *, struct sk_buff *, struct net_device *, u16 (*)(struct net_device *, struct sk_buff *, struct net_device *))’ {aka ‘short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *, short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *))’} [-Werror=incompatible-pointer-types]
 1710 |  .ndo_select_queue = rtw_select_queue,
      |                      ^~~~~~~~~~~~~~~~
/usr/src/rtl8192du/os_dep/os_intfs.c:1710:22: note: (near initialization for ‘rtw_netdev_if2_ops.ndo_select_queue’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:279: /usr/src/rtl8192du/os_dep/os_intfs.o] Error 1
make[1]: *** [Makefile:1600: _module_/usr/src/rtl8192du] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.2.5-200.fc30.x86_64'
make: *** [Makefile:610: modules] Error 2

**Comment by lwfinger** [comment]
Did you do a 'git pull'?

This compile failure was fixed May 31.

**Comment by dbrazziel** [comment]
I had been doing weekly 'git-fetch' via cron job. Will do a 'git-pull' now
and retry. If that works I will
change the cron job to do 'g-p'. Thank you!

**Comment by dbrazziel** [comment]
git pull https://github.com/lwfinger/rtl8192du -v
fatal: not a git repository (or any of the parent directories): .git

**Comment by dbrazziel** [comment]
Forgive my git ignorance. I hit it with a 'git clone' hammer and now the
compile works. I'll study up
on git and try to implement regular 'git pull'. Thanks again.

**Comment by lwfinger** [comment]
I'll help you. From the directory CREATED by the 'git clone', all you need is 'git pull'.  That simple command will update the files.
