### ISSUE TITLE
One of two interfaces raised

### ISSUE THREAD

**Issue by dbrazziel** [lwfinger/rtl8192du#79]
I'm not sure when two interfaces started appearing on this Netgear 600 (Belkin F9L1101V2), maybe they've been there all along and I just didn't notice. I see two interfaces being initialized but only one associates with the router. The link speed for one is 300 Mb/s, I'm wondering if it's possible to raise the second one and get 600 Mb/s total.

[Tue Sep 10 07:57:33 2019] RTL8192DU: rtw_ndev_init(wlan0)
[Tue Sep 10 07:57:33 2019] RTL8192DU: rtw_ndev_init(wlan1)

ifconfig output:

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.12  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 2600:6c65:767f:deef:7d2a:b651:7c2a:1024  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::b49f:6d41:67f2:b051  prefixlen 64  scopeid 0x20<link>
        inet6 2600:6c65:767f:deef:0:65df:e3f8:d1ec  prefixlen 128  scopeid 0x0<global>
        ether b4:75:0e:6e:e5:e0  txqueuelen 1000  (Ethernet)
        RX packets 2572  bytes 726883 (709.8 KiB)
        RX errors 0  dropped 2  overruns 0  frame 0
        TX packets 2650  bytes 1163435 (1.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether b6:75:0e:6e:e5:e0  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 589  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

Should both interfaces get lit by design, or is this a localized hardware / software configuration issue? I am using this on Debian kernel 5.2.0-2-amd64 on a dual core Pentium D desktop. Never seen more than one interface active.

**Comment by lwfinger** [comment]
There has likely always been two. The first way to get two is if you have a card with dual radios - 2.4 and 5 G. As far as I know, all RTL8192DU chips have both bands. The other way is with a configuration variable that makes two per radio, but I doubt that this is the case for you.

If your AP is not dual band, then the 5G interface does you no good.

**Comment by dbrazziel** [comment]
5G is working great for me, and the router advertises up to 1300 Mb/s on
the wireless band. Radio capacity from client to router shouldn't be a
problem. I'm just wondering why the lamp doesn't get lit on the other
interface. This isn't really a 'problem', more a question if I can
understand how to make the current config go faster. By the way, than k you
for your excellent work maintaing this out of kernel tree driver. Well
done, sir!

**Comment by lwfinger** [comment]
I do not know if it is possible to bond the 2.4 and the 5G in Linux, but I do know that it would be unlikely to be worth the effort and the resulting lack of stability.

You AP may advertise AC 1300, but the 8192DU is an 802.11N, not 802.11AC. Now you are down to 600 Mbps maximum, but wifi is a half-duplex medium, thus 300 Mbps is a more likely absolute maximum when there is absolutely no interference. In a moderately noisy environment, I measure 114 Mbps download and 76 Mbps upload speeds. That is pretty good got 802.11n in the real world. There are likely inefficiencies that could be fixed, but I have more pressing problems. If you get close to 100 Mbps and a stable connection, then count your blessings.
