### ISSUE TITLE
modprobe: FATAL

### ISSUE THREAD

**Issue by Twsitle** [lwfinger/rtl8192du#83]
modprobe: FATAL: Module rtl8192du not found in directory /lib/modules/5.4.0-26-generic

I hardly know any programming, so I just followed the instructions on this page.
Was nice and simple, but the last step didn't work.
Above is what the console output was.

**Comment by lwfinger** [comment]
I need a lot more than that info to help. Post ALL the output for "make" and ":sudo make install". I'm sure you overlooked a previous error,

**Comment by Twsitle** [comment]
<pre><font color="#8AE234"><b>ole@ole-MS-7971</b></font>:<font color="#729FCF"><b>~</b></font>$ git clone https://github.com/lwfinger/rtl8192du.git
Cloning into &apos;rtl8192du&apos;...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 7678 (delta 7), reused 13 (delta 5), pack-reused 7653
Receiving objects: 100% (7678/7678), 13.22 MiB | 9.23 MiB/s, done.
Resolving deltas: 100% (6134/6134), done.
<font color="#8AE234"><b>ole@ole-MS-7971</b></font>:<font color="#729FCF"><b>~</b></font>$ cd rtl8192du
<font color="#8AE234"><b>ole@ole-MS-7971</b></font>:<font color="#729FCF"><b>~/rtl8192du</b></font>$ make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.4.0-26-generic/build M=/home/ole/rtl8192du  modules
make[1]: Entering directory &apos;/usr/src/linux-headers-5.4.0-26-generic&apos;
  CC [M]  /home/ole/rtl8192du/core/rtw_cmd.o
  CC [M]  /home/ole/rtl8192du/core/rtw_security.o
  CC [M]  /home/ole/rtl8192du/core/rtw_debug.o
  CC [M]  /home/ole/rtl8192du/core/rtw_io.o
  CC [M]  /home/ole/rtl8192du/core/rtw_ioctl_query.o
  CC [M]  /home/ole/rtl8192du/core/rtw_ioctl_set.o
  CC [M]  /home/ole/rtl8192du/core/rtw_ieee80211.o
  CC [M]  /home/ole/rtl8192du/core/rtw_mlme.o
  CC [M]  /home/ole/rtl8192du/core/rtw_mlme_ext.o
  CC [M]  /home/ole/rtl8192du/core/rtw_wlan_util.o
  CC [M]  /home/ole/rtl8192du/core/rtw_pwrctrl.o
  CC [M]  /home/ole/rtl8192du/core/rtw_rf.o
  CC [M]  /home/ole/rtl8192du/core/rtw_recv.o
  CC [M]  /home/ole/rtl8192du/core/rtw_sta_mgt.o
  CC [M]  /home/ole/rtl8192du/core/rtw_ap.o
  CC [M]  /home/ole/rtl8192du/core/rtw_xmit.o
  CC [M]  /home/ole/rtl8192du/core/rtw_p2p.o
  CC [M]  /home/ole/rtl8192du/core/rtw_tdls.o
  CC [M]  /home/ole/rtl8192du/core/rtw_br_ext.o
  CC [M]  /home/ole/rtl8192du/core/rtw_iol.o
  CC [M]  /home/ole/rtl8192du/core/rtw_sreset.o
  CC [M]  /home/ole/rtl8192du/core/rtw_efuse.o
  CC [M]  /home/ole/rtl8192du/hal/hal_intf.o
  CC [M]  /home/ole/rtl8192du/hal/hal_com.o
  CC [M]  /home/ole/rtl8192du/hal/dm.o
  CC [M]  /home/ole/rtl8192du/hal/usb_ops_linux.o
  CC [M]  /home/ole/rtl8192du/hal/rtl8192d_hal_init.o
  CC [M]  /home/ole/rtl8192du/hal/rtl8192d_phycfg.o
  CC [M]  /home/ole/rtl8192du/hal/rtl8192d_rf6052.o
  CC [M]  /home/ole/rtl8192du/hal/rtl8192d_dm.o
  CC [M]  /home/ole/rtl8192du/hal/rtl8192d_rxdesc.o
  CC [M]  /home/ole/rtl8192du/hal/rtl8192d_cmd.o
  CC [M]  /home/ole/rtl8192du/hal/usb_halinit.o
  CC [M]  /home/ole/rtl8192du/hal/rtl8192du_led.o
  CC [M]  /home/ole/rtl8192du/hal/rtl8192du_xmit.o
  CC [M]  /home/ole/rtl8192du/hal/rtl8192du_recv.o
  CC [M]  /home/ole/rtl8192du/hal/rtl8192d_xmit.o
  CC [M]  /home/ole/rtl8192du/hal/Hal8192DUHWImg.o
  CC [M]  /home/ole/rtl8192du/os_dep/osdep_service.o
  CC [M]  /home/ole/rtl8192du/os_dep/os_intfs.o
  CC [M]  /home/ole/rtl8192du/os_dep/usb_intf.o
  CC [M]  /home/ole/rtl8192du/os_dep/usb_ops_linux.o
  CC [M]  /home/ole/rtl8192du/os_dep/ioctl_linux.o
  CC [M]  /home/ole/rtl8192du/os_dep/xmit_linux.o
  CC [M]  /home/ole/rtl8192du/os_dep/mlme_linux.o
  CC [M]  /home/ole/rtl8192du/os_dep/recv_linux.o
  CC [M]  /home/ole/rtl8192du/os_dep/ioctl_cfg80211.o
  CC [M]  /home/ole/rtl8192du/os_dep/wifi_regd.o
  CC [M]  /home/ole/rtl8192du/os_dep/rtw_android.o
  CC [M]  /home/ole/rtl8192du/os_dep/platform_ops.o
  CC [M]  /home/ole/rtl8192du/os_dep/rtw_proc.o
  LD [M]  /home/ole/rtl8192du/8192du.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC [M]  /home/ole/rtl8192du/8192du.mod.o
  LD [M]  /home/ole/rtl8192du/8192du.ko
make[1]: Leaving directory &apos;/usr/src/linux-headers-5.4.0-26-generic&apos;
<font color="#8AE234"><b>ole@ole-MS-7971</b></font>:<font color="#729FCF"><b>~/rtl8192du</b></font>$ sudo make install
[sudo] password for ole:       
install -p -m 644 8192du.ko  /lib/modules/5.4.0-26-generic/kernel/drivers/net/wireless/
/sbin/depmod -a 5.4.0-26-generic
<font color="#8AE234"><b>ole@ole-MS-7971</b></font>:<font color="#729FCF"><b>~/rtl8192du</b></font>$ sudo modprobe rtl8192du
modprobe: FATAL: Module rtl8192du not found in directory /lib/modules/5.4.0-26-generic
</pre>

**Comment by lwfinger** [comment]
I know you are a beginner, but you need to read the output and think a little. The build output shows "LD [M]  /home/ole/rtl8192du/8192du.ko". Even though README.md says  "sudo modprobe rtl8192du", you should allow the possibility that the documentation is wrong. In any case, if you had rebooted, your wifi would work.

I have fixed README.md.

**Comment by Twsitle** [comment]
You are correct, I hope to do better next time.
